import { useState, useEffect, useCallback, Fragment } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  getSolutionTracker,
  addSolutionRow,
  updateSolutionRow,
  deleteSolutionRow,
} from '../services/api.js';
import { usePermissions } from '../hooks/usePermissions.js';

// ── Status colours ────────────────────────────────────────────────────────────
const STATUS_COLORS = {
  'Won':        { bg: '#d1fae5', color: '#065f46' },
  'Lost':       { bg: '#fee2e2', color: '#991b1b' },
  'In Process': { bg: '#fef3c7', color: '#92400e' },
};
const BD_STATUS_OPTIONS  = ['In Process', 'Won', 'Lost'];
const SOL_STATUS_OPTIONS = ['Pending', 'In Progress', 'Submitted', 'Approved', 'Rejected'];

function pill(label, opts = {}) {
  const c = STATUS_COLORS[label] || { bg: 'var(--border)', color: 'var(--text)' };
  return (
    <span style={{
      fontSize: 11, fontWeight: 700, padding: '2px 8px',
      borderRadius: 12, background: c.bg, color: c.color,
      whiteSpace: 'nowrap', ...opts,
    }}>{label || '—'}</span>
  );
}

// ── Empty form templates ───────────────────────────────────────────────────────
// Auto-generated by Excel formulas — never sent to PA:
//   SNo, BD S No, Sol S No, Internal TAT, Date of Submission by Sol team
const EMPTY_BD = {
  proposalId: '', clientName: '', clientPoc: '', contactNumber: '',
  dateOfDiscussion: '', clientExpectedDate: '', bdMonth: '',
  programTopic: '', proposalVersion: 'V1', bdStatus: 'In Process', bdProposalValue: '',
  submissionToClient: '',
};
const EMPTY_SOL = {
  proposalId: '', solutionTopic: '', solutionMonth: '', programType: '',
  engagementType: '', lineOfService: '', typeOfService: '', developmentCategory: '',
  solutionValue: '', status: 'Pending', remarks: '', proposalV1Link: '',
};

// ── Shared Input Component ────────────────────────────────────────────────────
function Field({ label, children, half }) {
  return (
    <div style={{ gridColumn: half ? 'span 1' : 'span 2', display: 'flex', flexDirection: 'column', gap: 4 }}>
      <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</label>
      {children}
    </div>
  );
}
const inp = {
  padding: '8px 10px', borderRadius: 6, border: '1px solid var(--border)',
  background: 'var(--surface)', color: 'var(--text)', fontSize: 13, width: '100%',
  boxSizing: 'border-box',
};

// ── Fixed dropdown option lists ────────────────────────────────────────────────
const PROGRAM_TYPE_OPTS     = ['Standard', 'Customized'];
const ENGAGEMENT_TYPE_OPTS  = ['Standalone', 'Journey'];
const LINE_OF_SERVICE_OPTS  = ['Training', 'Talent Management', 'HR Services', 'Coaching', 'Other'];
const TYPE_OF_SERVICE_OPTS  = ['Facilitation', 'Coaching', 'Assessment & Development Centres', 'Success Presentation'];
const DEV_CATEGORY_OPTS     = [
  'Power Skills Enablement',
  'Leadership Development',
  'DEI & Culture Building',
  'Consulting & Talent Management',
  'Digital & Business Transformation',
  'Commercial & Sales Enablement (CSE)',
  'Creative Solutions (CS)',
  'Assessment & Development Centers',
];

/**
 * ComboSelect — dropdown with fixed options + "Other (type your own)" fallback.
 * Syncs with external `value` so it stays correct when the form is reset or
 * pre-filled from an existing record.
 */
function ComboSelect({ options, value, onChange, placeholder }) {
  const isPreset    = options.includes(value);
  const [showCustom, setShowCustom] = useState(!isPreset && !!value);
  const [customText, setCustomText] = useState(!isPreset ? (value || '') : '');

  // Sync when value changes externally (e.g., pre-fill from existing record)
  useEffect(() => {
    const preset = options.includes(value);
    setShowCustom(!preset && !!value);
    if (!preset) setCustomText(value || '');
    else setCustomText('');
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value]);

  const selectVal = showCustom ? '__custom__' : (value || '');

  return (
    <>
      <select style={inp} value={selectVal} onChange={e => {
        if (e.target.value === '__custom__') {
          setShowCustom(true);
          onChange(customText);
        } else {
          setShowCustom(false);
          setCustomText('');
          onChange(e.target.value);
        }
      }}>
        <option value="">— Select —</option>
        {options.map(o => <option key={o} value={o}>{o}</option>)}
        <option value="__custom__">Other (type your own…)</option>
      </select>
      {showCustom && (
        <input
          style={{ ...inp, marginTop: 6 }}
          placeholder={placeholder || 'Type custom value…'}
          value={customText}
          onChange={e => { setCustomText(e.target.value); onChange(e.target.value); }}
        />
      )}
    </>
  );
}

// ── Proposal ID auto-generator ────────────────────────────────────────────────
// Finds the largest numeric suffix across all existing Proposal IDs and increments it.
// e.g. ["P ID 088", "P ID 090"] → "P ID 091"
function generateNextPid(existingPids) {
  if (!existingPids || existingPids.length === 0) return 'P ID 001';
  const pairs = existingPids
    .map(pid => { const m = String(pid).match(/^(.*?)(\d+)$/); return m ? [m[1], m[2]] : null; })
    .filter(Boolean);
  if (pairs.length === 0) return 'P ID 001';
  pairs.sort((a, b) => parseInt(a[1], 10) - parseInt(b[1], 10));
  const [prefix, digits] = pairs[pairs.length - 1];
  const next = String(parseInt(digits, 10) + 1).padStart(digits.length, '0');
  return prefix + next;
}

// ── BD Modal ──────────────────────────────────────────────────────────────────
function BDModal({ initial, onSave, onClose, saving, bdRows }) {
  const isEdit = !!initial?.sno;

  // Compute existing PIDs and auto-generated next PID (add mode only)
  const existingPids = isEdit
    ? []
    : [...new Set((bdRows || []).map(r => r.proposalId).filter(Boolean))];
  const nextPid = isEdit ? '' : generateNextPid(existingPids);

  // Pre-fill proposalId with the generated ID when opening in add mode
  const [form, setForm] = useState(() => {
    const base = initial ? { ...initial } : { ...EMPTY_BD };
    if (!isEdit && !base.proposalId) base.proposalId = nextPid;
    return base;
  });
  // Tracks which option is selected in the Proposal ID dropdown (add mode only)
  const [pidSelect, setPidSelect] = useState('__new__');

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  // Auto-derive BD Month (e.g. "Sep 2026") whenever Date of Discussion changes
  function handleDateChange(dateVal) {
    set('dateOfDiscussion', dateVal);
    if (dateVal) {
      const [y, mo, d] = dateVal.split('-').map(Number);
      const formatted = new Date(y, mo - 1, d)
        .toLocaleString('en-US', { month: 'short', year: 'numeric' });
      set('bdMonth', formatted);
    }
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: 'var(--card)', borderRadius: 12, padding: 28, width: '100%', maxWidth: 680, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <h2 style={{ margin: 0, fontSize: 18 }}>{isEdit ? 'Edit BD Entry' : 'Add BD Entry'}</h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: 'var(--muted)' }}>✕</button>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>

          {/* ── Proposal ID — smart dropdown in add mode, plain text in edit ── */}
          {isEdit ? (
            <Field label="Proposal ID *" half>
              <input style={inp} value={form.proposalId} onChange={e => set('proposalId', e.target.value)} placeholder="e.g. P ID 001" />
            </Field>
          ) : (
            <Field label="Proposal ID *" half>
              <select
                style={inp}
                value={pidSelect}
                onChange={e => {
                  const val = e.target.value;
                  setPidSelect(val);
                  if (val === '__new__') {
                    // Reset to a blank form with the new auto-generated PID
                    setForm({ ...EMPTY_BD, proposalId: nextPid });
                  } else {
                    // Find the most-recent row with this PID and pre-fill all fields
                    const match = (bdRows || []).find(r => r.proposalId === val);
                    if (match) {
                      setForm({
                        ...EMPTY_BD,
                        ...match,
                        proposalId: val,
                        sno: '',                   // clear row key → treated as new row
                        dateOfDiscussion: '',       // dates are typically different each session
                        clientExpectedDate: '',
                        bdMonth: '',
                      });
                    } else {
                      set('proposalId', val);
                    }
                  }
                }}
              >
                <option value="__new__">➕ New Proposal ID — {nextPid}</option>
                {existingPids.map(pid => (
                  <option key={pid} value={pid}>{pid}</option>
                ))}
              </select>
              {pidSelect !== '__new__' && (
                <p style={{ margin: '4px 0 0', fontSize: 11, color: 'var(--muted)' }}>
                  Adding another entry to existing proposal <strong>{form.proposalId}</strong>
                </p>
              )}
            </Field>
          )}

          <Field label="Client Name *" half><input style={inp} value={form.clientName} onChange={e => set('clientName', e.target.value)} /></Field>
          <Field label="Client POC" half><input style={inp} value={form.clientPoc} onChange={e => set('clientPoc', e.target.value)} /></Field>
          <Field label="Contact Number" half><input style={inp} value={form.contactNumber} onChange={e => set('contactNumber', e.target.value)} /></Field>

          {/* ── Date of Discussion — auto-fills BD Month on change ── */}
          <Field label="Date of Discussion" half>
            <input
              type="date"
              style={inp}
              value={form.dateOfDiscussion}
              onChange={e => handleDateChange(e.target.value)}
            />
          </Field>
          <Field label="Client Expt" half><input type="date" style={inp} value={form.clientExpectedDate} onChange={e => set('clientExpectedDate', e.target.value)} /></Field>

          {/* ── BD Month — auto-filled from date; user can still override ── */}
          <Field label="BD Month" half>
            <input
              style={inp}
              value={form.bdMonth}
              onChange={e => set('bdMonth', e.target.value)}
              placeholder="Auto-filled from date (e.g. Sep 2026)"
            />
          </Field>
          <Field label="Program Topic" half><input style={inp} value={form.programTopic} onChange={e => set('programTopic', e.target.value)} /></Field>
          <Field label="Proposal Version" half>
            <input style={inp} value={form.proposalVersion} onChange={e => set('proposalVersion', e.target.value)} placeholder="V1" />
          </Field>
          <Field label="BD Status" half>
            <select style={inp} value={form.bdStatus} onChange={e => set('bdStatus', e.target.value)}>
              {BD_STATUS_OPTIONS.map(s => <option key={s}>{s}</option>)}
            </select>
          </Field>
          <Field label="BD Proposal Value"><input style={inp} value={form.bdProposalValue} onChange={e => set('bdProposalValue', e.target.value)} placeholder="₹ Amount" /></Field>
          <Field label="Date of Submission to Client" half><input type="date" style={inp} value={form.submissionToClient} onChange={e => set('submissionToClient', e.target.value)} /></Field>
        </div>
        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
          <button onClick={onClose} disabled={saving} style={{ padding: '8px 18px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer' }}>Cancel</button>
          <button onClick={() => onSave(form)} disabled={saving || !form.proposalId.trim() || !form.clientName.trim()} style={{ padding: '8px 22px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: (saving || !form.proposalId.trim() || !form.clientName.trim()) ? 'not-allowed' : 'pointer', opacity: (saving || !form.proposalId.trim() || !form.clientName.trim()) ? 0.5 : 1 }}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </div>
        {(!form.proposalId.trim() || !form.clientName.trim()) && (
          <p style={{ margin: '8px 0 0', fontSize: 12, color: '#ef4444', textAlign: 'right' }}>* Proposal ID and Client Name are required</p>
        )}
      </div>
    </div>
  );
}

// ── Solution Modal ─────────────────────────────────────────────────────────────
// proposalId is always known from the BD row context — no picker shown
function SolModal({ initial, proposalId, onSave, onClose, saving }) {
  const [form, setForm] = useState({ ...(initial || EMPTY_SOL), proposalId });
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const isEdit = !!initial?.sno;

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: 'var(--card)', borderRadius: 12, padding: 28, width: '100%', maxWidth: 680, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <div>
            <h2 style={{ margin: 0, fontSize: 18 }}>{isEdit ? 'Edit Solution Item' : 'Add Solution Item'}</h2>
            <p style={{ margin: '4px 0 0', fontSize: 12, color: 'var(--muted)' }}>
              Proposal: <strong style={{ color: 'var(--accent)' }}>{proposalId}</strong>
            </p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: 'var(--muted)' }}>✕</button>
        </div>
        {/* Solution Month — auto-generated by Excel formula, display only */}
        {form.solutionMonth && (
          <div style={{ marginBottom: 14, padding: '8px 12px', background: 'rgba(99,102,241,0.06)', borderRadius: 8, display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Solution Month</span>
            <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>{form.solutionMonth}</span>
            <span style={{ fontSize: 10, color: 'var(--muted)', marginLeft: 'auto' }}>Auto-generated by Excel</span>
          </div>
        )}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <Field label="Solution Topic *"><input style={inp} value={form.solutionTopic} onChange={e => set('solutionTopic', e.target.value)} /></Field>
          <Field label="Program Type" half>
            <ComboSelect options={PROGRAM_TYPE_OPTS} value={form.programType} onChange={v => set('programType', v)} />
          </Field>
          <Field label="Engagement Type" half>
            <ComboSelect options={ENGAGEMENT_TYPE_OPTS} value={form.engagementType} onChange={v => set('engagementType', v)} />
          </Field>
          <Field label="Line of Service" half>
            <ComboSelect options={LINE_OF_SERVICE_OPTS} value={form.lineOfService} onChange={v => set('lineOfService', v)} />
          </Field>
          <Field label="Type of Service" half>
            <ComboSelect options={TYPE_OF_SERVICE_OPTS} value={form.typeOfService} onChange={v => set('typeOfService', v)} />
          </Field>
          <Field label="Development Category" half>
            <ComboSelect options={DEV_CATEGORY_OPTS} value={form.developmentCategory} onChange={v => set('developmentCategory', v)} />
          </Field>
          <Field label="Solution Value" half><input style={inp} value={form.solutionValue} onChange={e => set('solutionValue', e.target.value)} placeholder="₹ Amount" /></Field>
          <Field label="Remarks"><textarea style={{ ...inp, resize: 'vertical', minHeight: 56 }} value={form.remarks} onChange={e => set('remarks', e.target.value)} /></Field>
          <Field label="Proposal V1 Link2"><input style={inp} value={form.proposalV1Link} onChange={e => set('proposalV1Link', e.target.value)} placeholder="https://..." /></Field>
          <Field label="Status" half>
            <select style={inp} value={form.status} onChange={e => set('status', e.target.value)}>
              {SOL_STATUS_OPTIONS.map(s => <option key={s}>{s}</option>)}
            </select>
          </Field>
        </div>
        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
          <button onClick={onClose} disabled={saving} style={{ padding: '8px 18px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer' }}>Cancel</button>
          <button onClick={() => onSave(form)} disabled={saving || !form.proposalId || !form.solutionTopic.trim()} style={{ padding: '8px 22px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: (saving || !form.proposalId || !form.solutionTopic.trim()) ? 'not-allowed' : 'pointer', opacity: (saving || !form.proposalId || !form.solutionTopic.trim()) ? 0.5 : 1 }}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </div>
        {(!form.proposalId || !form.solutionTopic.trim()) && (
          <p style={{ margin: '8px 0 0', fontSize: 12, color: '#ef4444', textAlign: 'right' }}>* Proposal ID and Solution Topic are required</p>
        )}
      </div>
    </div>
  );
}

// ── Delete Confirm Dialog ──────────────────────────────────────────────────────
// type='bd' with linkedCount > 0 → cascade warning (BD + all Sol rows deleted together).
// type='bd' with linkedCount = 0 OR type='sol' → simple single-row confirm.
function DeleteDialog({ label, onConfirm, onCancel, saving, type, linkedCount }) {
  const isCascade = type === 'bd' && linkedCount > 0;
  const totalRows  = linkedCount + 1; // anchor + sol rows

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100 }}>
      <div style={{ background: 'var(--card)', borderRadius: 10, padding: 28, maxWidth: 440, width: '90%', textAlign: 'center', boxShadow: '0 12px 40px rgba(0,0,0,0.3)' }}>
        {isCascade ? (
          <>
            <div style={{ fontSize: 36, marginBottom: 12 }}>⚠️</div>
            <h3 style={{ margin: '0 0 6px', color: '#b45309' }}>Delete BD Entry + All Solutions?</h3>
            <p style={{ margin: '0 0 12px', fontWeight: 700, fontSize: 14 }}>{label}</p>
            <div style={{ background: '#fef3c7', border: '1px solid #fbbf24', borderRadius: 8, padding: '12px 14px', margin: '0 0 20px', fontSize: 13, color: '#92400e', textAlign: 'left' }}>
              This will permanently delete <strong>{totalRows} rows</strong>:<br />
              <span style={{ display: 'block', marginTop: 6 }}>• 1 BD anchor row (this entry)</span>
              <span style={{ display: 'block' }}>• <strong>{linkedCount} linked solution row{linkedCount !== 1 ? 's' : ''}</strong> (Sol S No A – {String.fromCharCode(64 + linkedCount)})</span>
              <span style={{ display: 'block', marginTop: 8, fontWeight: 700 }}>This cannot be undone.</span>
            </div>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button onClick={onCancel} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer', fontWeight: 600 }}>Cancel</button>
              <button onClick={onConfirm} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: 'none', background: '#ef4444', color: '#fff', fontWeight: 700, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1 }}>
                {saving ? 'Deleting…' : `Delete All (${totalRows} rows)`}
              </button>
            </div>
          </>
        ) : (
          <>
            <div style={{ fontSize: 36, marginBottom: 12 }}>🗑️</div>
            <h3 style={{ margin: '0 0 8px' }}>Delete this entry?</h3>
            <p style={{ margin: '0 0 20px', color: 'var(--muted)', fontSize: 14 }}>{label}</p>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button onClick={onCancel} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={onConfirm} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: 'none', background: '#ef4444', color: '#fff', fontWeight: 700, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1 }}>
                {saving ? 'Deleting…' : 'Delete'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ── Main Page ──────────────────────────────────────────────────────────────────
export default function SolutionTracker({ onRefreshed, view }) {
  const navigate = useNavigate();
  const { canCreate } = usePermissions();

  const [rows, setRows]       = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState('');
  const [search, setSearch]   = useState('');
  // Set of proposalIds whose Sol rows are currently expanded
  const [expanded, setExpanded] = useState(new Set());

  // Modal state
  // solModal: null | { mode:'add', lockedPid:string } | { mode:'edit', row:obj }
  const [bdModal, setBdModal]     = useState(null);
  const [solModal, setSolModal]   = useState(null);
  const [delTarget, setDelTarget] = useState(null);
  const [saving, setSaving]       = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const data = await getSolutionTracker();
      setRows(data);
      onRefreshed?.(new Date().toLocaleTimeString());
    } catch (e) {
      setError(e.message || 'Failed to load data');
    } finally {
      setLoading(false);
    }
  }, [onRefreshed]);

  useEffect(() => { load(); }, [load]);

  // ── Toggle expand/collapse for a proposal ──────────────────────────────────
  function toggleExpand(pid) {
    setExpanded(prev => {
      const next = new Set(prev);
      if (next.has(pid)) next.delete(pid);
      else next.add(pid);
      return next;
    });
  }

  // ── Derived data ──────────────────────────────────────────────────────────
  // One BD anchor row per unique Proposal ID
  const bdRows = (() => {
    const seen = new Set();
    return rows
      .filter(r => r.proposalId)
      .filter(r => {
        const k = r.proposalId;
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
      })
      .filter(r => !search || [r.proposalId, r.clientName, r.programTopic, r.bdStatus, r.bdMonth].join(' ').toLowerCase().includes(search.toLowerCase()));
  })();

  // Sol rows grouped by proposalId
  function getSolRows(pid) {
    return rows.filter(r => r.proposalId === pid && r.solutionTopic);
  }


  // ── CRUD handlers ─────────────────────────────────────────────────────────
  async function handleSaveBD(form) {
    setSaving(true);
    try {
      // Use != null so sno=0 is treated as a valid row key (truthy check would fail for 0)
      if (form.sno != null && form.sno !== '') {
        // ── Edit existing BD anchor row ──────────────────────────────────────
        await updateSolutionRow(form.sno, form);

        // Propagate submissionToClient to every other sol row under this P ID
        // so all Excel rows reflect the same BD-level date.
        if (form.submissionToClient) {
          const otherRows = rows.filter(
            r => r.proposalId === form.proposalId &&
                 String(r.sno) !== String(form.sno)
          );
          await Promise.all(
            otherRows.map(r => updateSolutionRow(r.sno, { ...r, submissionToClient: form.submissionToClient }))
          );
        }
      } else {
        // ── New BD entry ─────────────────────────────────────────────────────
        const existingAnchor = rows.find(r => r.proposalId === form.proposalId && r.bdSNo);
        if (existingAnchor) {
          await updateSolutionRow(existingAnchor.sno, form);
          // Propagate submissionToClient to other rows too
          if (form.submissionToClient) {
            const otherRows = rows.filter(
              r => r.proposalId === form.proposalId &&
                   String(r.sno) !== String(existingAnchor.sno)
            );
            await Promise.all(
              otherRows.map(r => updateSolutionRow(r.sno, { ...r, submissionToClient: form.submissionToClient }))
            );
          }
        } else {
          await addSolutionRow(form);
        }
      }
      setBdModal(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  async function handleSaveSol(form) {
    setSaving(true);
    try {
      let payload = { ...form };

      if (!form.sno && form.proposalId) {
        const anchor = rows.find(r => r.proposalId === form.proposalId);
        if (anchor) {
          payload = {
            ...payload,
            clientName:         anchor.clientName         || payload.clientName,
            clientPoc:          anchor.clientPoc          || payload.clientPoc,
            contactNumber:      anchor.contactNumber      || payload.contactNumber,
            dateOfDiscussion:   anchor.dateOfDiscussion   || payload.dateOfDiscussion,
            clientExpectedDate: anchor.clientExpectedDate || payload.clientExpectedDate,
            bdMonth:            anchor.bdMonth            || payload.bdMonth,
            programTopic:       anchor.programTopic       || payload.programTopic,
            proposalVersion:    anchor.proposalVersion    || payload.proposalVersion,
            bdStatus:           anchor.bdStatus           || payload.bdStatus,
            bdProposalValue:    anchor.bdProposalValue    || payload.bdProposalValue,
            submissionToClient: anchor.submissionToClient || payload.submissionToClient,
          };

          const hasSolRows = rows.some(r => r.proposalId === form.proposalId && r.solutionTopic);
          if (!hasSolRows) {
            await updateSolutionRow(anchor.sno, payload);
            setSolModal(null);
            await load();
            return;
          }
        }
      }

      if (form.sno) {
        await updateSolutionRow(form.sno, payload);
      } else {
        await addSolutionRow(payload);
      }
      setSolModal(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  const linkedSolCount = delTarget?.type === 'bd'
    ? rows.filter(r => r.proposalId === delTarget.proposalId && r.solutionTopic).length
    : 0;

  async function handleDelete() {
    if (!delTarget) return;
    setSaving(true);
    try {
      if (delTarget.type === 'bd') {
        const allRows = rows.filter(r => r.proposalId === delTarget.proposalId);
        for (const r of allRows) {
          await deleteSolutionRow(r.sno);
        }
      } else {
        await deleteSolutionRow(delTarget.sno);
      }
      setDelTarget(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  // ── Shared cell styles ────────────────────────────────────────────────────
  const thStyle = {
    padding: '10px 12px', fontWeight: 700, fontSize: 11, color: 'var(--muted)',
    textTransform: 'uppercase', letterSpacing: '0.05em', whiteSpace: 'nowrap',
    borderBottom: '2px solid var(--border)', background: 'var(--surface)',
  };
  const tdStyle = { padding: '11px 12px', verticalAlign: 'middle' };

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div style={{ padding: '24px 28px', maxWidth: 1400, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 800 }}>
            {view === 'bd' ? '🎯 BD Tracker' : '💡 Solution Tracker'}
          </h1>
          <p style={{ margin: '4px 0 0', color: 'var(--muted)', fontSize: 13 }}>
            BD pipeline with linked solution items — click a row to expand
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <input
            placeholder="Search…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ ...inp, width: 220 }}
          />
          <button onClick={load} style={{ padding: '8px 14px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer', fontSize: 13 }}>🔄 Refresh</button>

        </div>
      </div>

      {/* Main Card */}
      <div style={{ background: 'var(--card)', borderRadius: 10, padding: 0, boxShadow: '0 2px 8px rgba(0,0,0,0.06)', overflow: 'hidden' }}>
        {loading && <div style={{ textAlign: 'center', padding: 48, color: 'var(--muted)' }}>Loading…</div>}
        {error   && <div style={{ textAlign: 'center', padding: 48, color: '#ef4444' }}>⚠ {error}</div>}

        {!loading && !error && (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr style={{ textAlign: 'left' }}>
                  <th style={{ ...thStyle, width: 36, textAlign: 'center' }}></th>
                  <th style={thStyle}>BD S No</th>
                  <th style={thStyle}>Proposal ID</th>
                  <th style={thStyle}>Client Name</th>
                  <th style={thStyle}>Program Topic</th>
                  <th style={thStyle}>BD Month</th>
                  <th style={thStyle}>BD Status</th>
                  <th style={thStyle}>Proposal Value</th>
                  {view !== 'bd' && <th style={thStyle}>Sol Items</th>}
                  <th style={thStyle}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {bdRows.length === 0 && (
                  <tr>
                    <td colSpan={view === 'bd' ? 9 : 10} style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>
                      No BD entries found. Click <strong>+ Add BD Entry</strong> to create one.
                    </td>
                  </tr>
                )}

                {bdRows.map((r, i) => {
                  const solItems = getSolRows(r.proposalId);
                  const isOpen   = expanded.has(r.proposalId);
                  const hasSols  = solItems.length > 0;

                  return (
                    <Fragment key={`group-${r.proposalId}-${i}`}>
                      {/* ── BD Primary Row ── */}
                      <tr
                        style={{
                          borderBottom: isOpen ? 'none' : '1px solid var(--border)',
                          background: isOpen ? 'var(--surface)' : 'transparent',
                          transition: 'background 0.15s',
                          cursor: 'pointer',
                        }}
                        onClick={() => toggleExpand(r.proposalId)}
                        onMouseEnter={e => { if (!isOpen) e.currentTarget.style.background = 'var(--surface)'; }}
                        onMouseLeave={e => { if (!isOpen) e.currentTarget.style.background = 'transparent'; }}
                      >
                        {/* Chevron toggle */}
                        <td style={{ ...tdStyle, textAlign: 'center', width: 36 }}>
                          <span style={{
                            display: 'inline-block',
                            transition: 'transform 0.2s',
                            transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)',
                            fontSize: 11, color: 'var(--muted)', userSelect: 'none',
                          }}>▶</span>
                        </td>
                        <td style={tdStyle}>
                          <span style={{ fontWeight: 700, background: 'var(--border)', borderRadius: 4, padding: '2px 7px', fontSize: 12 }}>#{r.bdSNo || r.sno}</span>
                        </td>
                        <td style={{ ...tdStyle, fontWeight: 700 }}>{r.proposalId}</td>
                        <td style={tdStyle}>{r.clientName}</td>
                        <td style={{ ...tdStyle, maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.programTopic || '—'}</td>
                        <td style={tdStyle}>{r.bdMonth || '—'}</td>
                        <td style={tdStyle}>{pill(r.bdStatus)}</td>
                        <td style={tdStyle}>{r.bdProposalValue ? `₹${r.bdProposalValue}` : '—'}</td>
                        {view !== 'bd' && (
                          <td style={tdStyle}>
                            {hasSols ? (
                              <span style={{ fontSize: 11, fontWeight: 600, background: '#ede9fe', color: '#6d28d9', borderRadius: 10, padding: '2px 8px' }}>
                                {solItems.length} sol
                              </span>
                            ) : (
                              <span style={{ fontSize: 11, color: 'var(--muted)' }}>—</span>
                            )}
                          </td>
                        )}
                        <td style={tdStyle}>
                          <span style={{ fontSize: 11, color: 'var(--muted)', fontStyle: 'italic' }}>Manage in BD Tracker</span>
                        </td>
                      </tr>

                      {/* ── Expanded Sol Panel ── */}
                      {isOpen && (
                        <tr>
                          <td colSpan={view === 'bd' ? 9 : 10} style={{ padding: 0, borderBottom: '2px solid var(--accent)', background: 'var(--surface)' }}>
                            <div style={{ paddingLeft: 48, paddingRight: 16, paddingBottom: 16, paddingTop: 8 }}>

                              {view === 'bd' ? (
                                /* ── BD Tracker expanded: show remaining BD fields only ── */
                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '10px 24px', padding: '12px 14px', background: 'rgba(99,102,241,0.05)', borderRadius: 8, fontSize: 13 }}>
                                  <div>
                                    <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 3 }}>Client POC</div>
                                    <div>{r.clientPoc || '—'}</div>
                                  </div>
                                  <div>
                                    <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 3 }}>Contact Number</div>
                                    <div>{r.contactNumber || '—'}</div>
                                  </div>
                                  <div>
                                    <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 3 }}>Date of Discussion</div>
                                    <div>{r.dateOfDiscussion || '—'}</div>
                                  </div>
                                  <div>
                                    <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 3 }}>Client Expected Date</div>
                                    <div>{r.clientExpectedDate || '—'}</div>
                                  </div>
                                  <div>
                                    <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 3 }}>Proposal Version</div>
                                    <div>{r.proposalVersion || '—'}</div>
                                  </div>
                                </div>
                              ) : (
                                /* ── Solution Tracker expanded: BD detail strip + Sol items ── */
                                <>
                                  <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap', padding: '8px 12px', background: 'rgba(99,102,241,0.06)', borderRadius: 8, marginBottom: 10, fontSize: 12 }}>
                                    {r.clientPoc && <span><span style={{ color: 'var(--muted)' }}>POC:</span> {r.clientPoc}</span>}
                                    {r.contactNumber && <span><span style={{ color: 'var(--muted)' }}>Contact:</span> {r.contactNumber}</span>}
                                    {r.dateOfDiscussion && <span><span style={{ color: 'var(--muted)' }}>Discussion:</span> {r.dateOfDiscussion}</span>}
                                    {r.clientExpectedDate && <span><span style={{ color: 'var(--muted)' }}>Client Expt:</span> {r.clientExpectedDate}</span>}
                                    {r.proposalVersion && <span><span style={{ color: 'var(--muted)' }}>Version:</span> {r.proposalVersion}</span>}
                                  </div>

                                  {solItems.length > 0 ? (
                                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12, marginBottom: 8 }}>
                                      <thead>
                                        <tr>
                                          {['Sol S No', 'Sol Month', 'Solution Topic', 'Line of Service', 'Type of Service', 'Dev Category', 'Sol Value', 'Status', 'Submitted to Client', 'Actions'].map(h => (
                                            <th key={h} style={{ padding: '6px 10px', fontWeight: 700, fontSize: 10, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.04em', textAlign: 'left', borderBottom: '1px solid var(--border)', whiteSpace: 'nowrap' }}>{h}</th>
                                          ))}
                                        </tr>
                                      </thead>
                                      <tbody>
                                        {solItems.map((s, si) => (
                                          <tr key={`sol-${s.sno}-${si}`} style={{ borderBottom: '1px solid var(--border)' }}
                                            onMouseEnter={e => e.currentTarget.style.background = 'rgba(99,102,241,0.04)'}
                                            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                                            <td style={{ padding: '8px 10px' }}>
                                              <span style={{ fontWeight: 700, background: '#ede9fe', color: '#6d28d9', borderRadius: 4, padding: '2px 7px', fontSize: 11 }}>{s.solSNo || '—'}</span>
                                            </td>
                                            <td style={{ padding: '8px 10px', whiteSpace: 'nowrap' }}>{s.solutionMonth || '—'}</td>
                                            <td style={{ padding: '8px 10px', maxWidth: 180, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: 600 }}>{s.solutionTopic}</td>
                                            <td style={{ padding: '8px 10px' }}>{s.lineOfService || '—'}</td>
                                            <td style={{ padding: '8px 10px' }}>{s.typeOfService || '—'}</td>
                                            <td style={{ padding: '8px 10px' }}>{s.developmentCategory || '—'}</td>
                                            <td style={{ padding: '8px 10px' }}>{s.solutionValue ? `₹${s.solutionValue}` : '—'}</td>
                                            <td style={{ padding: '8px 10px' }}>{pill(s.status)}</td>
                                            <td style={{ padding: '8px 10px' }}>{r.submissionToClient || '—'}</td>
                                            <td style={{ padding: '8px 10px' }}>
                                              <div style={{ display: 'flex', gap: 5 }}>
                                                <button
                                                  onClick={() => setSolModal({ mode: 'edit', row: s })}
                                                  style={{ padding: '3px 8px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--card)', cursor: 'pointer', fontSize: 11 }}
                                                >✏️</button>
                                                <button
                                                  onClick={() => setDelTarget({ sno: s.sno, label: `SNo ${s.sno} — ${s.proposalId} / ${s.solutionTopic}`, type: 'sol' })}
                                                  style={{ padding: '3px 8px', borderRadius: 4, border: '1px solid #fca5a5', background: '#fee2e2', color: '#991b1b', cursor: 'pointer', fontSize: 11 }}
                                                >🗑️</button>
                                                {canCreate('engagement') && (
                                                  <button
                                                    title="Add to Engagement Calendar"
                                                    onClick={() => navigate('/engagement', {
                                                      state: {
                                                        prefill: {
                                                          company:     r.clientName       || '',
                                                          topic:       s.solutionTopic    || '',
                                                          serviceType: s.typeOfService    || '',
                                                          sector:      s.developmentCategory || '',
                                                        },
                                                      },
                                                    })}
                                                    style={{ padding: '3px 8px', borderRadius: 4, border: '1px solid #a5b4fc', background: '#ede9fe', color: '#5b21b6', cursor: 'pointer', fontSize: 11, whiteSpace: 'nowrap' }}
                                                  >📅</button>
                                                )}
                                              </div>
                                            </td>
                                          </tr>
                                        ))}
                                      </tbody>
                                    </table>
                                  ) : (
                                    <p style={{ margin: '4px 0 8px', fontSize: 12, color: 'var(--muted)' }}>No solution items yet for this proposal.</p>
                                  )}

                                  <button
                                    onClick={() => setSolModal({ mode: 'add', lockedPid: r.proposalId })}
                                    style={{ padding: '6px 14px', borderRadius: 6, border: '1px dashed var(--accent)', background: 'transparent', color: 'var(--accent)', fontWeight: 700, cursor: 'pointer', fontSize: 12 }}
                                  >+ Add Solution Item</button>
                                </>
                              )}
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })}
              </tbody>
            </table>
            <div style={{ padding: '10px 16px', color: 'var(--muted)', fontSize: 12 }}>
              {bdRows.length} proposal{bdRows.length !== 1 ? 's' : ''}
            </div>
          </div>
        )}
      </div>

      {/* ── Modals ── */}
      {(bdModal === 'add' || (bdModal && typeof bdModal === 'object')) && (
        <BDModal
          initial={bdModal === 'add' ? null : bdModal}
          onSave={handleSaveBD}
          onClose={() => setBdModal(null)}
          saving={saving}
          bdRows={bdRows}
        />
      )}

      {solModal && solModal.mode === 'add' && (
        <SolModal
          initial={null}
          proposalId={solModal.lockedPid}
          onSave={handleSaveSol}
          onClose={() => setSolModal(null)}
          saving={saving}
        />
      )}
      {solModal && solModal.mode === 'edit' && (
        <SolModal
          initial={solModal.row}
          proposalId={solModal.row.proposalId}
          onSave={handleSaveSol}
          onClose={() => setSolModal(null)}
          saving={saving}
        />
      )}

      {delTarget && (
        <DeleteDialog
          label={delTarget.label}
          onConfirm={handleDelete}
          onCancel={() => setDelTarget(null)}
          saving={saving}
          type={delTarget.type}
          linkedCount={linkedSolCount}
        />
      )}
    </div>
  );
}
