import { useState, useEffect, useCallback } from 'react';
import {
  getSolutionTracker,
  addSolutionRow,
  updateSolutionRow,
  deleteSolutionRow,
} from '../services/api.js';

// ── Status colours ────────────────────────────────────────────────────────────
const STATUS_COLORS = {
  'Won':        { bg: '#d1fae5', color: '#065f46' },
  'Lost':       { bg: '#fee2e2', color: '#991b1b' },
  'In Process': { bg: '#fef3c7', color: '#92400e' },
};
const BD_STATUS_OPTIONS  = ['In Process', 'Won', 'Lost'];
const SOL_STATUS_OPTIONS = ['Pending', 'In Progress', 'Submitted', 'Approved', 'Rejected'];

function pill(label, opts = {}) {
  const c = STATUS_COLORS[label] || { bg: 'var(--border)', color: 'var(--text)' };
  return (
    <span style={{
      fontSize: 11, fontWeight: 700, padding: '2px 8px',
      borderRadius: 12, background: c.bg, color: c.color,
      whiteSpace: 'nowrap', ...opts,
    }}>{label || '—'}</span>
  );
}

// ── Empty form templates ───────────────────────────────────────────────────────
// Auto-generated by Excel formulas — never sent to PA:
//   SNo, BD S No, Sol S No, Internal TAT, Date of Submission by Sol team
const EMPTY_BD = {
  proposalId: '', clientName: '', clientPoc: '', contactNumber: '',
  dateOfDiscussion: '', clientExpectedDate: '', bdMonth: '',
  programTopic: '', proposalVersion: 'V1', bdStatus: 'In Process', bdProposalValue: '',
};
const EMPTY_SOL = {
  proposalId: '', solutionTopic: '', solutionMonth: '', programType: '',
  engagementType: '', lineOfService: '', typeOfService: '', developmentCategory: '',
  solutionValue: '', status: 'Pending', remarks: '', proposalV1Link: '',
  submissionToErTeam: '',
};

// ── Shared Input Component ────────────────────────────────────────────────────
function Field({ label, children, half }) {
  return (
    <div style={{ gridColumn: half ? 'span 1' : 'span 2', display: 'flex', flexDirection: 'column', gap: 4 }}>
      <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</label>
      {children}
    </div>
  );
}
const inp = {
  padding: '8px 10px', borderRadius: 6, border: '1px solid var(--border)',
  background: 'var(--surface)', color: 'var(--text)', fontSize: 13, width: '100%',
  boxSizing: 'border-box',
};

// ── BD Modal ──────────────────────────────────────────────────────────────────
function BDModal({ initial, onSave, onClose, saving }) {
  const [form, setForm] = useState(initial || EMPTY_BD);
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const isEdit = !!initial?.sno;

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: 'var(--card)', borderRadius: 12, padding: 28, width: '100%', maxWidth: 680, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <h2 style={{ margin: 0, fontSize: 18 }}>{isEdit ? 'Edit BD Entry' : 'Add BD Entry'}</h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: 'var(--muted)' }}>✕</button>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <Field label="Proposal ID *" half><input style={inp} value={form.proposalId} onChange={e => set('proposalId', e.target.value)} placeholder="e.g. P001" /></Field>
          <Field label="Client Name *" half><input style={inp} value={form.clientName} onChange={e => set('clientName', e.target.value)} /></Field>
          <Field label="Client POC" half><input style={inp} value={form.clientPoc} onChange={e => set('clientPoc', e.target.value)} /></Field>
          <Field label="Contact Number" half><input style={inp} value={form.contactNumber} onChange={e => set('contactNumber', e.target.value)} /></Field>
          <Field label="Date of Discusssion" half><input type="date" style={inp} value={form.dateOfDiscussion} onChange={e => set('dateOfDiscussion', e.target.value)} /></Field>
          <Field label="Client Expt" half><input type="date" style={inp} value={form.clientExpectedDate} onChange={e => set('clientExpectedDate', e.target.value)} /></Field>
          <Field label="BD Month" half><input style={inp} value={form.bdMonth} onChange={e => set('bdMonth', e.target.value)} placeholder="e.g. Sep 2026" /></Field>
          <Field label="Program Topic" half><input style={inp} value={form.programTopic} onChange={e => set('programTopic', e.target.value)} /></Field>
          <Field label="Proposal Version" half>
            <input style={inp} value={form.proposalVersion} onChange={e => set('proposalVersion', e.target.value)} placeholder="V1" />
          </Field>
          <Field label="BD Status" half>
            <select style={inp} value={form.bdStatus} onChange={e => set('bdStatus', e.target.value)}>
              {BD_STATUS_OPTIONS.map(s => <option key={s}>{s}</option>)}
            </select>
          </Field>
          <Field label="BD Proposal Value"><input style={inp} value={form.bdProposalValue} onChange={e => set('bdProposalValue', e.target.value)} placeholder="₹ Amount" /></Field>
        </div>
        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
          <button onClick={onClose} disabled={saving} style={{ padding: '8px 18px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer' }}>Cancel</button>
          <button onClick={() => onSave(form)} disabled={saving || !form.proposalId.trim() || !form.clientName.trim()} style={{ padding: '8px 22px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: (saving || !form.proposalId.trim() || !form.clientName.trim()) ? 'not-allowed' : 'pointer', opacity: (saving || !form.proposalId.trim() || !form.clientName.trim()) ? 0.5 : 1 }}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </div>
        {(!form.proposalId.trim() || !form.clientName.trim()) && (
          <p style={{ margin: '8px 0 0', fontSize: 12, color: '#ef4444', textAlign: 'right' }}>* Proposal ID and Client Name are required</p>
        )}
      </div>
    </div>
  );
}

// ── Solution Modal ─────────────────────────────────────────────────────────────
function SolModal({ initial, proposalIds, onSave, onClose, saving }) {
  const [form, setForm] = useState(initial || EMPTY_SOL);
  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const isEdit = !!initial?.sno;

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: 'var(--card)', borderRadius: 12, padding: 28, width: '100%', maxWidth: 680, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <h2 style={{ margin: 0, fontSize: 18 }}>{isEdit ? 'Edit Solution Item' : 'Add Solution Item'}</h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: 'var(--muted)' }}>✕</button>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <Field label="Proposal ID *" half>
            <select style={inp} value={form.proposalId} onChange={e => set('proposalId', e.target.value)}>
              <option value="">— Select —</option>
              {proposalIds.map(id => <option key={id}>{id}</option>)}
            </select>
          </Field>
          <Field label="Solution Month" half><input style={inp} value={form.solutionMonth} onChange={e => set('solutionMonth', e.target.value)} placeholder="e.g. Sep 2026" /></Field>
          <Field label="Solution Topic *"><input style={inp} value={form.solutionTopic} onChange={e => set('solutionTopic', e.target.value)} /></Field>
          <Field label="Program Type" half><input style={inp} value={form.programType} onChange={e => set('programType', e.target.value)} /></Field>
          <Field label="Engagement Type" half><input style={inp} value={form.engagementType} onChange={e => set('engagementType', e.target.value)} /></Field>
          <Field label="Line of Service" half><input style={inp} value={form.lineOfService} onChange={e => set('lineOfService', e.target.value)} /></Field>
          <Field label="Type of Service" half><input style={inp} value={form.typeOfService} onChange={e => set('typeOfService', e.target.value)} /></Field>
          <Field label="Development Category" half><input style={inp} value={form.developmentCategory} onChange={e => set('developmentCategory', e.target.value)} /></Field>
          <Field label="Solution Value" half><input style={inp} value={form.solutionValue} onChange={e => set('solutionValue', e.target.value)} placeholder="₹ Amount" /></Field>
          <Field label="Status" half>
            <select style={inp} value={form.status} onChange={e => set('status', e.target.value)}>
              {SOL_STATUS_OPTIONS.map(s => <option key={s}>{s}</option>)}
            </select>
          </Field>
          <Field label="Date of submission ER Team" half><input type="date" style={inp} value={form.submissionToErTeam} onChange={e => set('submissionToErTeam', e.target.value)} /></Field>
          <Field label="Remarks"><textarea style={{ ...inp, resize: 'vertical', minHeight: 56 }} value={form.remarks} onChange={e => set('remarks', e.target.value)} /></Field>
          <Field label="Proposal V1 Link2"><input style={inp} value={form.proposalV1Link} onChange={e => set('proposalV1Link', e.target.value)} placeholder="https://..." /></Field>
        </div>
        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
          <button onClick={onClose} disabled={saving} style={{ padding: '8px 18px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer' }}>Cancel</button>
          <button onClick={() => onSave(form)} disabled={saving || !form.proposalId || !form.solutionTopic.trim()} style={{ padding: '8px 22px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: (saving || !form.proposalId || !form.solutionTopic.trim()) ? 'not-allowed' : 'pointer', opacity: (saving || !form.proposalId || !form.solutionTopic.trim()) ? 0.5 : 1 }}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </div>
        {(!form.proposalId || !form.solutionTopic.trim()) && (
          <p style={{ margin: '8px 0 0', fontSize: 12, color: '#ef4444', textAlign: 'right' }}>* Proposal ID and Solution Topic are required</p>
        )}
      </div>
    </div>
  );
}

// ── Delete Confirm Dialog ──────────────────────────────────────────────────────
// `blocked` = true means linked solutions exist; show a warning, no Delete button.
function DeleteDialog({ label, onConfirm, onCancel, saving, blocked, linkedCount }) {
  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1100 }}>
      <div style={{ background: 'var(--card)', borderRadius: 10, padding: 28, maxWidth: 420, width: '90%', textAlign: 'center', boxShadow: '0 12px 40px rgba(0,0,0,0.3)' }}>
        {blocked ? (
          <>
            <div style={{ fontSize: 36, marginBottom: 12 }}>⚠️</div>
            <h3 style={{ margin: '0 0 8px', color: '#b45309' }}>Cannot Delete BD Entry</h3>
            <p style={{ margin: '0 0 8px', fontWeight: 700, fontSize: 14 }}>{label}</p>
            <div style={{ background: '#fef3c7', border: '1px solid #fbbf24', borderRadius: 8, padding: '10px 14px', margin: '0 0 20px', fontSize: 13, color: '#92400e' }}>
              This BD entry has <strong>{linkedCount} linked solution item{linkedCount !== 1 ? 's' : ''}</strong>.<br />
              Delete all linked solutions first, then delete this entry.
            </div>
            <button onClick={onCancel} style={{ padding: '8px 24px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer', fontWeight: 600 }}>Close</button>
          </>
        ) : (
          <>
            <div style={{ fontSize: 36, marginBottom: 12 }}>🗑️</div>
            <h3 style={{ margin: '0 0 8px' }}>Delete this entry?</h3>
            <p style={{ margin: '0 0 20px', color: 'var(--muted)', fontSize: 14 }}>{label}</p>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button onClick={onCancel} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer' }}>Cancel</button>
              <button onClick={onConfirm} disabled={saving} style={{ padding: '8px 20px', borderRadius: 6, border: 'none', background: '#ef4444', color: '#fff', fontWeight: 700, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1 }}>
                {saving ? 'Deleting…' : 'Delete'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ── Main Page ──────────────────────────────────────────────────────────────────
export default function SolutionTracker({ onRefreshed, view }) {
  const [tab, setTab]         = useState(view || 'bd');   // 'bd' | 'sol'
  const [rows, setRows]       = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState('');
  const [search, setSearch]   = useState('');

  // Modal state
  const [bdModal, setBdModal]   = useState(null);   // null | 'add' | rowObj
  const [solModal, setSolModal] = useState(null);
  const [delTarget, setDelTarget] = useState(null); // { sno, label, type: 'bd'|'sol', proposalId? }
  const [saving, setSaving]     = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const data = await getSolutionTracker();
      setRows(data);
      onRefreshed?.(new Date().toLocaleTimeString());
    } catch (e) {
      setError(e.message || 'Failed to load data');
    } finally {
      setLoading(false);
    }
  }, [onRefreshed]);

  useEffect(() => { load(); }, [load]);

  // ── Derived views ─────────────────────────────────────────────────────────
  const bdRows = (() => {
    const seen = new Set();
    return rows
      .filter(r => r.proposalId)
      .filter(r => {
        const k = r.proposalId;
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
      })
      .filter(r => !search || [r.proposalId, r.clientName, r.programTopic, r.bdStatus].join(' ').toLowerCase().includes(search.toLowerCase()));
  })();

  const solRows = rows
    .filter(r => r.solutionTopic)
    .filter(r => !search || [r.proposalId, r.solutionTopic, r.lineOfService, r.status].join(' ').toLowerCase().includes(search.toLowerCase()));

  const proposalIds = [...new Set(rows.filter(r => r.proposalId).map(r => r.proposalId))];

  // ── CRUD handlers ─────────────────────────────────────────────────────────
  async function handleSaveBD(form) {
    setSaving(true);
    try {
      if (form.sno) {
        await updateSolutionRow(form.sno, form);
      } else {
        await addSolutionRow(form);
      }
      setBdModal(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  async function handleSaveSol(form) {
    setSaving(true);
    try {
      if (form.sno) {
        await updateSolutionRow(form.sno, form);
      } else {
        await addSolutionRow(form);
      }
      setSolModal(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  // For BD deletes: count solution rows that share this proposalId
  const linkedSolCount = delTarget?.type === 'bd'
    ? rows.filter(r => r.proposalId === delTarget.proposalId && r.solutionTopic).length
    : 0;

  async function handleDelete() {
    if (!delTarget) return;
    // Block if this is a BD entry with linked solutions
    if (delTarget.type === 'bd' && linkedSolCount > 0) return;
    setSaving(true);
    try {
      await deleteSolutionRow(delTarget.sno);
      setDelTarget(null);
      await load();
    } catch (e) {
      alert('Error: ' + e.message);
    } finally {
      setSaving(false);
    }
  }

  // ── Render ────────────────────────────────────────────────────────────────
  const tabStyle = (active) => ({
    padding: '9px 22px', border: 'none', cursor: 'pointer', fontWeight: 700,
    fontSize: 13, borderRadius: '8px 8px 0 0',
    background: active ? 'var(--card)' : 'transparent',
    color: active ? 'var(--accent)' : 'var(--muted)',
    borderBottom: active ? '2px solid var(--accent)' : '2px solid transparent',
  });

  return (
    <div style={{ padding: '24px 28px', maxWidth: 1300, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 800 }}>
            {view === 'bd' ? '🎯 BD Tracker' : view === 'sol' ? '💡 Solution Tracker' : '💡 Solution Tracker'}
          </h1>
          <p style={{ margin: '4px 0 0', color: 'var(--muted)', fontSize: 13 }}>
            {view === 'bd' ? 'Business Development proposals and pipeline' : view === 'sol' ? 'Solution line items linked to BD proposals' : 'BD Pipeline + Solution breakdown in one master view'}
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <input
            placeholder="Search…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ ...inp, width: 220 }}
          />
          <button onClick={load} style={{ padding: '8px 14px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', cursor: 'pointer', fontSize: 13 }}>🔄 Refresh</button>
          {(view === 'bd' || (!view && tab === 'bd')) && (
            <button onClick={() => setBdModal('add')} style={{ padding: '8px 18px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: 'pointer', fontSize: 13 }}>+ Add BD Entry</button>
          )}
          {(view === 'sol' || (!view && tab === 'sol')) && (
            <button onClick={() => setSolModal('add')} style={{ padding: '8px 18px', borderRadius: 6, border: 'none', background: 'var(--accent)', color: '#fff', fontWeight: 700, cursor: 'pointer', fontSize: 13 }}>+ Add Solution Item</button>
          )}
        </div>
      </div>

      {/* Tabs — only shown when no view prop is passed */}
      {!view && (
        <div style={{ display: 'flex', borderBottom: '1px solid var(--border)', marginBottom: 0 }}>
          <button style={tabStyle(tab === 'bd')}   onClick={() => setTab('bd')}>📋 BD View</button>
          <button style={tabStyle(tab === 'sol')}  onClick={() => setTab('sol')}>🔍 Solution View</button>
        </div>
      )}

      {/* Content */}
      <div style={{ background: 'var(--card)', borderRadius: '0 8px 8px 8px', padding: 20, boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}>
        {loading && <div style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>Loading…</div>}
        {error   && <div style={{ textAlign: 'center', padding: 40, color: '#ef4444' }}>⚠ {error}</div>}

        {/* ── BD VIEW ── */}
        {!loading && !error && tab === 'bd' && (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr style={{ background: 'var(--surface)', textAlign: 'left' }}>
                  {['BD S No', 'Proposal ID', 'Client Name', 'Program Topic', 'BD Month', 'BD Status', 'Proposal Value', 'Actions'].map(h => (
                    <th key={h} style={{ padding: '10px 12px', fontWeight: 700, fontSize: 11, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', whiteSpace: 'nowrap', borderBottom: '1px solid var(--border)' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {bdRows.length === 0 && (
                  <tr><td colSpan={8} style={{ textAlign: 'center', padding: 32, color: 'var(--muted)' }}>No BD entries found</td></tr>
                )}
                {bdRows.map((r, i) => (
                  <tr key={r.proposalId + i} style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.15s' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'var(--surface)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                    <td style={{ padding: '10px 12px' }}>
                      <span style={{ fontWeight: 700, background: 'var(--border)', borderRadius: 4, padding: '2px 7px', fontSize: 12 }}>#{r.bdSNo || r.sno}</span>
                    </td>
                    <td style={{ padding: '10px 12px', fontWeight: 700 }}>{r.proposalId}</td>
                    <td style={{ padding: '10px 12px' }}>{r.clientName}</td>
                    <td style={{ padding: '10px 12px', maxWidth: 220, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.programTopic}</td>
                    <td style={{ padding: '10px 12px' }}>{r.bdMonth || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{pill(r.bdStatus)}</td>
                    <td style={{ padding: '10px 12px' }}>{r.bdProposalValue ? `₹${r.bdProposalValue}` : '—'}</td>
                    <td style={{ padding: '10px 12px' }}>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button onClick={() => setBdModal(r)} style={{ padding: '4px 10px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer', fontSize: 12 }}>✏️ Edit</button>
                        <button onClick={() => setDelTarget({ sno: r.sno, label: `${r.proposalId} — ${r.clientName}`, type: 'bd', proposalId: r.proposalId })} style={{ padding: '4px 10px', borderRadius: 4, border: '1px solid #fca5a5', background: '#fee2e2', color: '#991b1b', cursor: 'pointer', fontSize: 12 }}>🗑️</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div style={{ marginTop: 12, color: 'var(--muted)', fontSize: 12 }}>{bdRows.length} proposal{bdRows.length !== 1 ? 's' : ''}</div>
          </div>
        )}

        {/* ── SOLUTION VIEW ── */}
        {!loading && !error && tab === 'sol' && (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr style={{ background: 'var(--surface)', textAlign: 'left' }}>
                  {['Sol S No', 'Proposal ID', 'Solution Topic', 'Line of Service', 'Type of Service', 'Dev Category', 'Solution Value', 'Status', 'Sol By', 'Sol To ER', 'Actions'].map(h => (
                    <th key={h} style={{ padding: '10px 12px', fontWeight: 700, fontSize: 11, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.05em', whiteSpace: 'nowrap', borderBottom: '1px solid var(--border)' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {solRows.length === 0 && (
                  <tr><td colSpan={11} style={{ textAlign: 'center', padding: 32, color: 'var(--muted)' }}>No solution items found</td></tr>
                )}
                {solRows.map((r, i) => (
                  <tr key={r.sno + '-' + i} style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.15s' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'var(--surface)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                    <td style={{ padding: '10px 12px' }}>
                      <span style={{ fontWeight: 700, background: 'var(--border)', borderRadius: 4, padding: '2px 7px', fontSize: 12 }}>{r.solSNo || '—'}</span>
                    </td>
                    <td style={{ padding: '10px 12px', fontWeight: 700 }}>{r.proposalId}</td>
                    <td style={{ padding: '10px 12px', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.solutionTopic}</td>
                    <td style={{ padding: '10px 12px' }}>{r.lineOfService || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{r.typeOfService || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{r.developmentCategory || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{r.solutionValue ? `₹${r.solutionValue}` : '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{pill(r.status)}</td>
                    <td style={{ padding: '10px 12px' }}>{r.submissionBySolTeam || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>{r.submissionToErTeam || '—'}</td>
                    <td style={{ padding: '10px 12px' }}>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button onClick={() => setSolModal(r)} style={{ padding: '4px 10px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--surface)', cursor: 'pointer', fontSize: 12 }}>✏️ Edit</button>
                        <button onClick={() => setDelTarget({ sno: r.sno, label: `${r.proposalId} — ${r.solutionTopic}`, type: 'sol' })} style={{ padding: '4px 10px', borderRadius: 4, border: '1px solid #fca5a5', background: '#fee2e2', color: '#991b1b', cursor: 'pointer', fontSize: 12 }}>🗑️</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div style={{ marginTop: 12, color: 'var(--muted)', fontSize: 12 }}>{solRows.length} solution item{solRows.length !== 1 ? 's' : ''}</div>
          </div>
        )}
      </div>

      {/* ── Modals ── */}
      {(bdModal === 'add' || (bdModal && typeof bdModal === 'object')) && (
        <BDModal
          initial={bdModal === 'add' ? null : bdModal}
          onSave={handleSaveBD}
          onClose={() => setBdModal(null)}
          saving={saving}
        />
      )}
      {(solModal === 'add' || (solModal && typeof solModal === 'object')) && (
        <SolModal
          initial={solModal === 'add' ? null : solModal}
          proposalIds={proposalIds}
          onSave={handleSaveSol}
          onClose={() => setSolModal(null)}
          saving={saving}
        />
      )}
      {delTarget && (
        <DeleteDialog
          label={delTarget.label}
          onConfirm={handleDelete}
          onCancel={() => setDelTarget(null)}
          saving={saving}
          blocked={delTarget.type === 'bd' && linkedSolCount > 0}
          linkedCount={linkedSolCount}
        />
      )}
    </div>
  );
}
